### ISSUE TITLE
TimeOfDay easily format to DateTime

### ISSUE THREAD

**Issue by dupiesdupreez** [subhamayd2/day_night_time_picker#1]
Is there any chance to get a method for this?

**Comment by subhamayd2** [comment]
Thanks for bringing this to my attention.

I normally use something similar to this:
```dart
TimeOfDay t;
final now = new DateTime.now();
return new DateTime(now.year, now.month, now.day, t.hour, t.minute);
```

But your suggestion would definitely make life much easier.  😁

**Comment by dupiesdupreez** [comment]
That's what I also ended up doing =)

And I guess that's really just me being lazy asking for this, haha so one day when you really have nothing to do you can throw it in 😁

Thanks for the quick response

**Comment by subhamayd2** [comment]
Updated.
Let me know, if you encounter any issues. 😄
