### ISSUE TITLE
on change not working

### ISSUE THREAD

**Issue by WAQAS039** [subhamayd2/day_night_time_picker#104]
i am using this code 
 showPicker(
                    isInlinePicker: true,
                    width: double.maxFinite,
                    elevation: 5,
                    borderRadius: 8.r,
                    value: _time,
                    dialogInsetPadding: EdgeInsets.only(bottom: 20.h),
                    height: 333.h,
                    hideButtons: true,
                    wheelHeight: 170.h,
                    // disableAutoFocusToNextInput: true,
                    themeData: ThemeData(
                        sliderTheme: SliderThemeData(
                            thumbColor: Colors.amber,
                            activeTrackColor: appColors,
                            inactiveTrackColor: AppColors.darkBrandingColor
                        )
                    ),
                    onChange: (Time) {
                      print(Time);
                    }
                ),
in onchange method i am trying to print the time value but i can not see any thing

**Comment by subhamayd2** [comment]
Could you try to run the example code once and check if that's working?

**Comment by WAQAS039** [comment]
it works when user press ok button but i actually hide the buttons, and what i want is when user change time so on change method should listen to changes in time and print the time object

**Comment by subhamayd2** [comment]
I think you need the onValueChange method
Mentioned in docs:
![image](https://user-images.githubusercontent.com/23093995/232289739-09d73832-ba78-4fe7-bb7a-a935fa7f6fbc.png)

**Comment by WAQAS039** [comment]
yes it is working now
