### ISSUE TITLE
fixed height showing white background.

### ISSUE THREAD

**Issue by Emon526** [subhamayd2/day_night_time_picker#106]
when the height is default i mean 400 it  is showing white space but when chnage the height 390 its gone.so i suggest make this responsive

**Comment by TheGlorySaint** [comment]
Hey @Emon526,


could you please provide me a minimal reproducible product? I have looked into that issue, but found nothing where a white space should be.

**Comment by Emon526** [comment]
i am using samsung s7  as my testing device
here is the code i used 
`showPicker(
      context: context,
      value: context.read<ReminderProvider>().time,
      onChange: (newTime) {
        context.read<ReminderProvider>().time = newTime;
      },
    );`

![Image of example](https://drive.google.com/uc?export=download&id=14SI-n4tRXymc-mhLB429OnJDbXMDY0YF
)

so i wish you can make it  responsive
@TheGlorySaint

**Comment by Emon526** [comment]
@TheGlorySaint
