### ISSUE TITLE
Screen is shifted when opening the dialog on iOS

### ISSUE THREAD

**Issue by omzer** [subhamayd2/day_night_time_picker#13]
I got the following result when I try to execute the code bellow:
```
  final rout = showPicker(
      context: context,
      value: TimeOfDay.now().replacing(minute: 30),
      iosStylePicker: !true,
      onChange: (t) => print(t),
      sunAsset: Image.asset('lib/images/sun.png'),
      moonAsset: Image.asset('lib/images/moon.png'),
      okText: 'ok'.tr,
      cancelText: 'cancel'.tr,
    );

    Navigator.of(context).push(rout);
```
![image](https://user-images.githubusercontent.com/23129313/101380711-861e3380-38be-11eb-8fc8-dd4f9bdaaeee.png)

It's worth noting that:
- Couldn't reproduce on Android.
- I'm using  iOS simulator iPhone Pro 12 Max 14.1.
- I'm using GetMaterialApp instead of MaterialApp as my main widget.
- Device locale is set  to Arabic (which is an RTL language).

**Comment by subhamayd2** [comment]
Could not replicate the issue.
