### ISSUE TITLE
[Feature request] - Select minutes before

### ISSUE THREAD

**Issue by henry2man** [subhamayd2/day_night_time_picker#25]
Hello. @subhamayd2 Congratulations on the component.

Would it be possible to have some parameter (by default false so as not to affect normal behavior) that would allow first to choose the minutes before the hours?

I am going to use the component with `displayHeader:false` to model the use case of choosing a duration that, in general, will always be expressed in minutes and not hours. Having the minutes preselected would help with the usability of the component.

Regards.

**Comment by subhamayd2** [comment]
Hi @henry2man,
Thanks for using the component.

When you say you want to pre-select the minutes, do you mean you want the minutes to be fixed in the picker? If so, you can pass a `TimeOfDay` with your minutes selected and then simply disable the minutes picker.

**Comment by henry2man** [comment]
I'll try to explain it better. 

In my use case I want to use the picker to get an indeterminate duration from the user.Normally this duration will always be a few minutes. When opening the current picker the first selection is the hours. You have to click on the minutes to select them. The proposed parameter would serve so that when opening the picker the minutes were already active, so that we save one click and improve the usability of the component.

**Comment by subhamayd2** [comment]
@henry2man Updated with a new prop `focusMinutePicker`.
Let me know, if that works for you.

**Comment by henry2man** [comment]
@subhamayd2 It works like a charm! 🚀
