### ISSUE TITLE
Expected a value of type 'SkDeletable', but got one of type 'Null' in Web

### ISSUE THREAD

**Issue by zphoenixz** [subhamayd2/day_night_time_picker#26]
This happens when clicking in time picker when running in web

The following TypeErrorImpl was thrown building DayNightTimePickerAndroid(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#25815]], state: _DayNightTimePickerAndroidState#f0eed):
Expected a value of type 'SkDeletable', but got one of type 'Null'

The relevant error-causing widget was
MaterialApp
lib/main.dart:86

**Comment by ReversedHourglass** [comment]
Same issue here

**Comment by subhamayd2** [comment]
This seems to be an issue in flutter itself.

See [here](https://github.com/flutter/flutter/issues/77258#issuecomment-822006335)

Anyways, I fixed the issue with a simple workaround - it should work fine now.

✌
