### ISSUE TITLE
Possibility to return Duration

### ISSUE THREAD

**Issue by DmitrijsD** [subhamayd2/day_night_time_picker#29]
Would be nice if we could get Duration from this dialog and setting maxHours to 24, not old Java time format 0-23.

**Comment by TheGlorySaint** [comment]
@DmitrijsD What do you mean from get the Duration? Do you mean for example that the Picked Time is the Hours and Minutes for a Timer?

For maxHours to 24, the Clock is running from 00:00:00 to 23:59:59 so there is no 24:00. It is from the ViewPoint where you watch there may be a 24:00 but on normal circumstances there is no 24:00. So the 2nd suggestion won't make it.

**Comment by TheGlorySaint** [comment]
Closing this issue to the inactivity from the Author
