### ISSUE TITLE
SUN/MOON images dissapair  when you change the minutes in 24 hour format

### ISSUE THREAD

**Issue by pablofridman** [subhamayd2/day_night_time_picker#3]
When you change the minutes in 24 hour format the SUN/MOON changes the position to the end of the widget. 

Nice component!!

**Comment by subhamayd2** [comment]
@pablofridman Thanks for pointing it out.
This issue has been fixed.
Please let me know, if you encounter any other issues. ✌️

**Comment by pablofridman** [comment]
works great!!! thanks!!!
