### ISSUE TITLE
Min - Max Hour for 12 Hour Format

### ISSUE THREAD

**Issue by rjtubera** [subhamayd2/day_night_time_picker#31]
Hi, how can I set the min max hour for the 12 hour format?

Our timings should be 10AM to 9PM.

I tried putting` minHour: 10 and maxHour: 21 `

but it doesn't accept it using the 12 hour format.

How can I make this work?

**Comment by rjtubera** [comment]
bump

**Comment by rjtubera** [comment]
Hi guys, any update on this?

**Comment by subhamayd2** [comment]
Hi,

I am looking into this.

Got caught up in some other work.

**Comment by rjtubera** [comment]
bump

**Comment by rjtubera** [comment]
bump

**Comment by AimanKyo97** [comment]
Hello?? how do i format time base on this

**Comment by subhamayd2** [comment]
The latest release should have the fix for this.
