### ISSUE TITLE
Bottom overflow in landscape on small phones (ie 720x1480)

### ISSUE THREAD

**Issue by samflink** [subhamayd2/day_night_time_picker#32]
Hi,

I encountered an issue on small phones. When used in landscape mode the date picker popup window is too large for the screen. A RenderFlex overflow error message is shown.

Steps to reproduce:
1. use a virtual device with a low resolution (Galaxy Nexus or something with 720x1280 or lower)
2. open the time picker as a popup (I used the example code)
3. turn device to landscape

![Screenshot_1630005777](https://user-images.githubusercontent.com/76847955/131024181-6aea4187-a7c1-4766-b36d-5afbd6d375d0.png)

Best regards,

Sam

**Comment by deviankim** [comment]
same here

**Comment by TheGlorySaint** [comment]
@samflink @deviankim Thank you for opening this issue.

I have looked at this issue and fixed it. There was also an issue with the iOS Style Inlinepicker on smaller devices.

**Comment by samflink** [comment]
@TheGlorySaint Thank you for fixing this :) I updated to version 1.0.5 and it works perfect now!

**Comment by TheGlorySaint** [comment]
> @TheGlorySaint Thank you for fixing this :) I updated to version 1.0.5 and it works perfect now!

You're welcome, glad I fixed your issue. Feel free to give that package a thumbs up at pub.dev
