### ISSUE TITLE
Keyboard input for web/desktop

### ISSUE THREAD

**Issue by NotHolst** [subhamayd2/day_night_time_picker#37]
Would be a better UX if web/desktop users were able to input using the keyboard.

**Comment by TheGlorySaint** [comment]
@NotHolst Good suggestion, could you please point out on how you thought it should work?

For example if pressed on the Hour and Minute then you get a Dialog where you can enter the time or not a Dialog and just typing?

**Comment by subhamayd2** [comment]
In my opinion, typing out the hour/minute would make the animation a bit weird.

**Comment by TheGlorySaint** [comment]
@subhamayd2 thought about the same, that's why I'm asking because it is weird, typing the Time.

**Comment by subhamayd2** [comment]
@TheGlorySaint Maybe we can try to use the keyboard's arrow keys to change the hour/minute?

**Comment by TheGlorySaint** [comment]
Closing this good issue because currently it is not planned to add this functionality
