### ISSUE TITLE
set is24HrFormat as true not work

### ISSUE THREAD

**Issue by jinjilynn** [subhamayd2/day_night_time_picker#49]
![image](https://user-images.githubusercontent.com/12596042/147878606-be32937d-9f00-40ee-8345-c37a9a426895.png)
it starts with 12 and not ends with 23 but with 11

**Comment by jinjilynn** [comment]
```dart
int getModifiedLabel(int value) {
    if (value == 0) {
      return 12;
    }
    if (value > 12) {
      return value - 12;
    }
    return value;
  }

```
may check this method

**Comment by TheGlorySaint** [comment]
Hi @jinjilynn,

Thank You for your comment. I'll take a look at it.

**Comment by TheGlorySaint** [comment]
@jinjilynn I found the Issue, fixed it and created a PR. In the next Release this Issue is fixed
