### ISSUE TITLE
[Feature Request] Minute interval option

### ISSUE THREAD

**Issue by edcmex** [subhamayd2/day_night_time_picker#5]
really like it. would be awesome if you had an interval option on the minutes. 0, 15, 30, 45

**Comment by SayWut** [comment]
It is not a dream anymore :D
He added it in the last update (Nov 4, 2020)

**Comment by subhamayd2** [comment]
Yeah, will publish it soon. Just got to make sure it didn't break anything.

**Comment by subhamayd2** [comment]
Hi,

This has been fixed in the new release.
Please let me know, if you encounter any issues.

Thanks.

**Comment by edcmex** [comment]
works like a charm! thank you

**Comment by monkeydaichan** [comment]
@subhamayd2 
Can you select interval option on the minutes. 0, 15, 30, 45?
I think can select only 1,5,10,15
