### ISSUE TITLE
How to change splash/hover color of cancel/ok button?

### ISSUE THREAD

**Issue by SittiphanSittisak** [subhamayd2/day_night_time_picker#52]
I don't see properties of the cancel/ok button. Is it possible to change splash/hover color?

**Comment by TheGlorySaint** [comment]
Hey @SittiphanSittisak,

Sorry, I hadn't the Time to look into it. I'll do it in the next two Days. But I think currently it is not possible, only the TextStyle is changeable.

If the buttons are not changeable, should all button be changeable?

**Comment by subhamayd2** [comment]
This was foolish on my part to not include fully customizable buttons. I think we should accept a `okButton` property and `cancelButton` property, then fallback to our default button if these properties were not provided.
Thanks @TheGlorySaint for looking into it.

**Comment by SittiphanSittisak** [comment]
It's interesting!
It's good if can put the widget instead ok/cancel button.
We can pop to close this dialog.

**Comment by TheGlorySaint** [comment]
PullRequest got merged into develop
