### ISSUE TITLE
Issue with meridiems for ios style

### ISSUE THREAD

**Issue by rafoolin** [subhamayd2/day_night_time_picker#54]
As you can see in the video, my phone is set to `20:04`, so the meridiem should continue to display `p.m` instead of `a.m` as the hour changes.

Here is the code.

```dart
import 'package:day_night_time_picker/day_night_time_picker.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: const Text('Open Time Picker'),
          onPressed: () {
            Navigator.of(context).push(
              showPicker(
                context: context,
                value: TimeOfDay.now(),
                iosStylePicker: true,
                onChange: (value) {
                  print(value.toString());
                },
              ),
            );
          },
        ),
      ),
    );
  }
}
```
![output](https://user-images.githubusercontent.com/54066251/156886882-e81f6937-47fb-44b1-bb40-e266a6d1cf0b.gif)

**Comment by TheGlorySaint** [comment]
Hi @rafoolin,

Your Time that you set in the Phone Settings do net influence the Timer Picker. If you pick 4AM the Sun is rising, and if you pick 2PM the Sun is at it's highest point.


If I got your feedback wrong, could you please explain it more, what you mean?

**Comment by rafoolin** [comment]
@TheGlorySaint  Hi, thanks for your response.

No, I didn't expect the package to match the real hour angle. In the video you can see that when I opened the dialog, the values are `08:04 p.m`, then when I change the hour to `9`, instead of showing `09:04 p.m` it switches to `a.m`.

I expect that `p.m` doesn't change to `a.m`.

**Comment by TheGlorySaint** [comment]
@rafoolin okay, now I see what you mean.

I'll let you know when I found a solution.

**Comment by tarunt815** [comment]
also having this issue. 

@TheGlorySaint any update on fix?

**Comment by saifb** [comment]
This is the bug: https://github.com/subhamayd2/day_night_time_picker/blob/7f901bd4c73fb96b3cd700ddb992f38a3a7aa0f7/lib/lib/day_night_timepicker_ios.dart#L67-L69

Changing the code to `final h = timeState!.time.hour;` fixes this regardless of whether the widget is 24 hr format or not.

**Comment by TheGlorySaint** [comment]
@tarunt815 Thank you for your headsup. @saifb was so kind and fixed the issue with a PR. I close this issue due to the fix
