### ISSUE TITLE
Issue with inline widget

### ISSUE THREAD

**Issue by vatsa1101** [subhamayd2/day_night_time_picker#58]
I'm facing an issues in fitting the inline widget using fittedBox, Flexible and Expanded. What should I do?

**Comment by TheGlorySaint** [comment]
@vatsa1101 I have looked into your issue and couldn't reproduce it.

Would it be possible for you to provide the Code to have a deeper look into your issue?

**Comment by TheGlorySaint** [comment]
Closed due to inactivity
