### ISSUE TITLE
onChangeDateTime call on null

### ISSUE THREAD

**Issue by git-maven** [subhamayd2/day_night_time_picker#6]
The method 'call' was called on null.
Receiver: null
Tried calling: call(Instance of 'TimeOfDay')

**Comment by subhamayd2** [comment]
Hi,

Could you provide more info? Like, code snippet, etc

Thanks.

**Comment by git-maven** [comment]
> Hi,
> 
> Could you provide more info? Like, code snippet, etc
> 
> Thanks.

Navigator.of(appContext).push(
                      showPicker(
                          context: appContext,
                          value: TimeOfDay.now(),
                          onChangeDateTime: (date){
                            print(date);
                          },
                          onChange: (newTime){
                            valueNotifier.value = '${newTime.hour}:${newTime.minute}';
                            handleTotal();
                          }),
                    )
so if i remove the function onChangeDateTime, it isnot any error

**Comment by git-maven** [comment]
so i think the params on onChangeDateTime is null

**Comment by subhamayd2** [comment]
Hi,

I checked and can't seem to reproduce this issue. Everything is working fine.
Please check your code.
