### ISSUE TITLE
Provide a way to override Cancel button behavior

### ISSUE THREAD

**Issue by markszente** [subhamayd2/day_night_time_picker#64]
### What
I suggest adding an optional `onCancel` parameter to override Cancel button behavior.

### Why
In my use case, I had to use the `rootNavigator` to show the dialog. Since the hard-coded behavior of the Cancel button is currently to call `Navigator.of(context).pop();`, it didn't work for me. 

I have already implemented these changes in my fork, so I could submit a PR if you wish.

**Comment by TheGlorySaint** [comment]
Hi @markszente,

that's a good idea. If you like, you can submit a PR and I can have a look at it.

**Comment by subhamayd2** [comment]
Published on pub.dev
