### ISSUE TITLE
FlatButton in readme is deprecated

### ISSUE THREAD

**Issue by guyluz11** [subhamayd2/day_night_time_picker#71]
FlatButton in readme example is deprecated.

As the IDE warrns

> FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.26.0-18.0

**Comment by TheGlorySaint** [comment]
Thanks for letting us know. Naming is fixed.
