### ISSUE TITLE
How to decrease the height of the picker box

### ISSUE THREAD

**Issue by Likenttt** [subhamayd2/day_night_time_picker#74]
Hi，
Thanks for your great work. I have one question how to decrease the height? I didn't find the parameter in the doc

![image](https://user-images.githubusercontent.com/26034018/181221066-7f1a565f-1719-4232-bb79-19f0be4095e0.png)

**Comment by TheGlorySaint** [comment]
@Likenttt I have added for the `createInlinePicker` a new option to size the wheel of the times and requested review for that. Please sit tight for public release you can add the PR in your pubspec.yaml to use the new Version before public release.
