### ISSUE TITLE
Any way to add a max width or height constraint to the popups?

### ISSUE THREAD

**Issue by taufiq-husain** [subhamayd2/day_night_time_picker#75]
`
                            TimeOfDay time = TimeOfDay.fromDateTime(_mondayStart);
                            Navigator.of(context).push(
                              showPicker(
                                context: context,
                                value: time,
                                onChange: (_) {},
                                minuteInterval: MinuteInterval.FIFTEEN,
                                onChangeDateTime: (DateTime dateTime) {
                                  setState(() {
                                    _mondayStart = dateTime;
                                  });
                                },
                              ),
                            );
`

I would like to add a maximum width to the popup. If an app needs to adapt from mobile to web (desktop), it can look quite weird to fill up a whole desktop/laptop monitor screen. It's the right approach for mobile devices, however. I can't figure out how to put a max width constraint for large screens.

**Comment by TheGlorySaint** [comment]
@taufiq-husain I have created a PR #78 for the height of the `createInlinePicker`.

Could you please add the PR to your project and test if that is what you want for the height, when I would add a new option for the width. 

HeadUp currently only for `createInlinePicker` and not `showPicker`.

**Comment by H4zh4n** [comment]
I'm guessing Mr. @taufiq-husain  wanted to have the ability to change the entire dialog width (same as me).

I'm using this lovely library on a windows application, the width of the dialog takes-up the entire screen which looks kinda weird for users.

![image](https://user-images.githubusercontent.com/47919702/216894989-143c0b4a-0911-41bf-b5c9-bc234acef17c.png)



If we could have a property to set the width (and/or height) of the dialog ourselves it would be really appreciated. essentially to make the dialog turn to something like this :
![image](https://user-images.githubusercontent.com/47919702/216895738-4c11f021-ccda-4424-975b-7798718229d6.png)



Maybe having it so we can do something like this :
```
Navigator.of(context).push(
    showPicker(
        context: context,
        width: 100, // <---- manually setting width of the dialog
        height: 300, // <---- manually setting height of the dialog
        value: _time,
        onChange: onTimeChanged,
    ),
);
```

**Comment by subhamayd2** [comment]
Fixed in the latest release.
