### ISSUE TITLE
Failed assertion: line 166 pos 15: 'value >= min && value <= max': is not true.

### ISSUE THREAD

**Issue by zhao6810** [subhamayd2/day_night_time_picker#8]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/material/slider.dart': Failed assertion: line 166 pos 15: 'value >= min && value <= max': is not true.
The relevant error-causing widget was:

**Comment by subhamayd2** [comment]
Hi,

Could you please provide the full error stack?

Thanks.
