### ISSUE TITLE
How to disable specific time?

### ISSUE THREAD

**Issue by vivasvan1** [subhamayd2/day_night_time_picker#80]
I want to make an appointment app.

I want to disable time slots which are altready booked so user are unable to select it.

For ex:
if an appointment is already been made for 9:30.
I want the slider to jump from 9:20 to 9:40 skipping 9:30.

Any idea on how can i acheive this?

**Comment by TheGlorySaint** [comment]
Hello @vivasvan1,


you have the property `value` where you can set the inital Time.

For example you can do something like this:

`TimeOfDay _time = TimeOfDay.now().replacing(hour: 11, minute: 30);`
Where you replace the current Hour and Minute with the value you specify. 

You can also create a onChange method for checking if the selected time is the already booked time.

```
void onTimeChanged(TimeOfDay newTime) {
    setState(() {
     if(newTime = bookTime){
     // error Handling here
     } else {
      _time = newTime;
       // handle succesfully time change here
    }
    });
  }
```

**Comment by vivasvan1** [comment]
Umm 🤔.

If i understand this correctly ... on change function will execute after the user has pressed "OK" button. Right?

So for my case: if i have 1 appointment left on that day.

Then the user will have to slide across all the  times to search for that available time.

What i want is the **slider itself to jump** from 9:20 to 9:40 skipping 9:30( which already booked )

For which i propose an argument like:

`disableTimestamps: List<DateTime> [ ]`

Does this make sense? Or maybe is this something too specific to my usecase?

I am currently using a simple dropDown form field with all the available times.

But i really love 💕 the animations in this package 📦😁.

**Comment by TheGlorySaint** [comment]
As written above,

`TimeOfDay _time = TimeOfDay.now().replacing(hour: 11, minute: 30);` can ab set to the `value` property as the initial time.
So when 11:20 is booked, the next available is then 11:30. If you want more, then this Package is currently not the right for you. Maybe later it can be. If you like you can create a PR with the things you want and we (the Team) discuss if this is something we want or not.

**Comment by vivasvan1** [comment]
Yeah, i think I am looking for something else. 

I will use dropDown button for my use-case which also works perfectly as i want.

Nevertheless thanks for quick reply and your help.

We can close the issue now

**Comment by TheGlorySaint** [comment]
@vivasvan1 You are welcome. Feel free to post a PR and i have a look at it.
