### ISSUE TITLE
Is there an option to be able to pick seconds too?

### ISSUE THREAD

**Issue by IsaiChristian** [subhamayd2/day_night_time_picker#81]
If there isnt, WOuld you be interested in a  pull request including it?

**Comment by subhamayd2** [comment]
Sounds good to me..
@TheGlorySaint thoughts on this?

**Comment by TheGlorySaint** [comment]
Hey @IsaiChristian,

currently, there is no option about picking seconds. For what use case do you think this could and would be used that exactly that needs to have seconds? Feel free to post a PR, I'll have a look at that then.

@subhamayd2 Why not having. I can't think about a use case but someone definitely can have a use case for this.

**Comment by IsaiChristian** [comment]
Well for me is that we are doing a trading journal were people have the option add their transactions manually, as we are focused on daytraders, some times 2 trades can happen in the same minute. this is just to save the info no too try to do anything programatically.

**Comment by subhamayd2** [comment]
Right now, the limitation that I found was that we are using `TimeOfDay` as the value, which doesn't have a `second` property.
The alternative is to use `DateTime` as the value - now by doing this we lose the `DayPeriod` property (i.e. the am/pm). 😞

Including `second` would be a lot of change and refactoring. If you are willing to contribute to this, that would be helpful.

**Comment by subhamayd2** [comment]
I have updated the picker to include `seconds` as well. It's available in the latest release.
