### ISSUE TITLE
Picker not reacting to new TimeOfDay-Value

### ISSUE THREAD

**Issue by myThorsten** [subhamayd2/day_night_time_picker#82]
Hallo folks :)

I just found your package and I really like it. I'm want to use the inline version of it. Then I got the idea to change to cancel-button to a new-button to quickly reset the value to now:
![image](https://user-images.githubusercontent.com/9773490/194608016-7c88766f-9fc6-4a1e-a821-c07f1f4d04d6.png)

Everytime I click the now-Button, I get this in the console:
![image](https://user-images.githubusercontent.com/9773490/194608477-587ab8d5-2d04-477e-95b3-4526bf5bcdb6.png)
So I am assuming that this should work. 

Unfortunately, the value in the inline-picker does not change. It stays at the previously set value.
![image](https://user-images.githubusercontent.com/9773490/194608993-003e258a-80dd-47c7-9a0d-89a303d0cfb4.png)

What am I doing wrong?

**Comment by TheGlorySaint** [comment]
Hey @myThorsten,

glad you found this package and you like it.


About your Problem:
I have checked your Problem and found out that the `createInlinePicker` Wheel (where you choose the time) is not rendering again when you use the `onCancle` Method.

Currently, I do not have the Time to look into your Issue. If you like to create a PR, feel free to do so. I review it. If not hopefully starting in November, i have the Time then to look fix your issue.

**Comment by TheGlorySaint** [comment]
Hey @myThorsten,


your issue should now be fixed. Thanks to the PR from @donttouchfranky.


To check out the Fix please use not the package from pub.dev use instead, while i contact the Package Owner to Release a new Version to pub.dev.
```
day_night_time_picker:
    git:
      url: git://github.com:subhamayd2/day_night_time_picker.git
      ref: develop
```
