### ISSUE TITLE
Using the picker as a standalone widget

### ISSUE THREAD

**Issue by emilekm2142** [subhamayd2/day_night_time_picker#9]
Could you allow to use the picker as a widget instead of a dialog?

**Comment by SayWut** [comment]
You can get the widget like so:

```dart
showPicker(
	value: TimeOfDay(hour: 8, minute: 0),
	onChange: (change) {},
  ).buildPage(context, null, null),
```

it is not the cleanest thing but it will do the job until will be a solution for this

**Comment by subhamayd2** [comment]
Hi,

Sorry for the delay.
Will definitely update the widget once I start feeling well.

Again, sorry for the delay. 😢

**Comment by SayWut** [comment]
BTW the `DayNightTimePickerIos` is the implementation of the picker for ios and it isn't private so you basically can use it like any other widget
but the `_DayNightTimePicker` which is the inplementation for android is private 
so for ios you are golden for android not so much

@subhamayd2 first of all have a good rest and I hope you will feel well soon :D 
secondly, you can basically create a method like `showDialog` (maybe `createTimePicker`) but that returns the widget instead showing a dialog

**Comment by subhamayd2** [comment]
@SayWut yeah will probably make the android one public, just like the ios.
I think that would be better than introducing another method.

**Comment by SayWut** [comment]
> @SayWut yeah will probably make the android one public, just like the ios.
> I think that would be better than introducing another method.

You can do both creating a method and making the android public
the beauty of a method is that it handles the different OS and returns the proper widget based on the OS, like the `showDialog` 
it will be super helpful instead of letting each developer that using this dependencie to handle it itself

**Comment by subhamayd2** [comment]
> You can do both creating a method and making the android public
> the beauty of a method is that it handles the different OS and returns the proper widget based on the OS, like the `showDialog` 
> it will be super helpful instead of letting each developer that using this dependencie to handle it itself

Yeah, that sounds good.

**Comment by subhamayd2** [comment]
Hi,

This has been fixed in the new release.
Please let me know, if you encounter any issues.

Thanks.

**Comment by SayWut** [comment]
@subhamayd2 Thanks for the method :D

BTW you can now use the `createInlinePicker()` method in the `showPicker()` method instead copy and paste basically the same code and it will look cleaner

**Comment by subhamayd2** [comment]
Yep. Will be doing a few refactors soon.
