### ISSUE TITLE
Auto-focus minutes after clicking/releasing hours slider

### ISSUE THREAD

**Issue by H4zh4n** [subhamayd2/day_night_time_picker#92]
Thanks for the lovely library.
I was wondering if it would be possible to make it so AFTER choosing the desired hour it automatically changes to choosing minutes.

This is how default TimePicker works. The user is picking hour, upon mouse/finger click/release the dial changes to picking minutes. this is just a _Quality of Life_ change for users.

# Default TimePicker :
![default](https://user-images.githubusercontent.com/47919702/216899524-c4d37d56-16e2-45a9-956a-fa7679f5c6e6.gif)

# This Library
User has to go all the way back to minutes to click then go back to Slider to change minutes : 
![current](https://user-images.githubusercontent.com/47919702/216899379-c8b9211a-1e17-4e86-9f8e-6415993d16d5.gif)
![current-click](https://user-images.githubusercontent.com/47919702/216899984-592b525c-4083-4eaa-8119-4da98e142106.gif)

# Desired Effect
Auto-change
![desired](https://user-images.githubusercontent.com/47919702/216900914-536d9fa8-c42a-48ae-8c82-ae693fe1e2b1.gif)

**Comment by subhamayd2** [comment]
Fixed in the latest release.
