### ISSUE TITLE
Flag to disable seconds

### ISSUE THREAD

**Issue by Gerstalexej** [subhamayd2/day_night_time_picker#94]
Hey there, great work with this package!
Could you add a flag to disable the newly introduced seconds like you have for disabling hours/minutes?

**Comment by subhamayd2** [comment]
By default `second` selector is hidden anyway.

**Comment by Gerstalexej** [comment]
Really? For me it's enabled and I don't know how to get rid of it

**Comment by subhamayd2** [comment]
Ohh. Okay I'll take a look

**Comment by Gerstalexej** [comment]
@subhamayd2 Unfortunately, on version 1.2.0+2 I still have this problem. No matter how flags is24HrFormat or iosStylePicker are set
