### ISSUE TITLE
Please increment major revision when introducing a breaking change

### ISSUE THREAD

**Issue by jonbhanson** [subhamayd2/day_night_time_picker#97]
Hello and thanks for your work on this package!

I just wanted to give some constructive feedback.  When you introduce a breaking change, such as those included in version 1.2.0, [Semantic Versioning item 9](https://semver.org/spec/v2.0.0-rc.1.html#spec-item-9) instructs that you should change the major version number.

In my case, I upgraded to version 1.2 expecting no breaking changes since it was not a major revision, and was surprised by the breaking changes.

Once again, I appreciate the work you've put into this,

Signed,
Another package developer.

**Comment by subhamayd2** [comment]
Thank you for that feedback. It was a silly mistake on my part - I should have been more careful about this.
I will definitely keep this in mind from next time.

**Comment by maltemedocs** [comment]
Thank you. I just had a look here whether this got already discussed. This package is way too nice for issues like this, I really appreciate this reaction.
