### ISSUE TITLE
Make "Cancel" Button Widget optional

### ISSUE THREAD

**Issue by qqjjjj** [subhamayd2/day_night_time_picker#98]
Hi, Thanks for creating this awesome packages.

Just have a suggestion if the CancelButton Widget can be optional as to force user to click OK.

Thanks!

Sample:
![localhost_53262_](https://user-images.githubusercontent.com/67450840/226180933-44c9894e-2b1b-444f-bb86-7925e29a86b0.png)

**Comment by qqjjjj** [comment]
#99

**Comment by TheGlorySaint** [comment]
Thanks for adding your PR. Marged it and closed comment.

I'll add you as a contributor for Code
